insert into circuito (cod_pais, nome, extensao)values (17, 'GP da Austrália - Melbourne', 5303);
insert into circuito (cod_pais, nome, extensao)values (18, 'GP da Malásia - Sepang', 5543);
insert into circuito (cod_pais, nome, extensao)values (19, 'GP do Bahrein - Sakhir', 5412);
insert into circuito (cod_pais, nome, extensao)values (3, 'GP da Espanha - Barcelona', 4627);
insert into circuito (cod_pais, nome, extensao)values (23, 'GP de Mônaco - Monte Carlo', 3340);
insert into circuito (cod_pais, nome, extensao)values (16, 'GP do Canadá - Montreal', 4361);
insert into circuito (cod_pais, nome, extensao)values (2, 'GP dos EUA - Indianápolis', 4192);
insert into circuito (cod_pais, nome, extensao)values (15, 'GP da França - Magny-Cours', 4411);
insert into circuito (cod_pais, nome, extensao)values (4, 'GP da Inglaterra - Silverstone', 5141);
insert into circuito (cod_pais, nome, extensao)values (6, 'GP da Alemanha - Nurburgring', 5148);
insert into circuito (cod_pais, nome, extensao)values (20, 'GP da Hungria - Hungaroring', 4381);
insert into circuito (cod_pais, nome, extensao)values (13, 'GP da Turquia - Istambul', 5338);
insert into circuito (cod_pais, nome, extensao)values (5, 'GP da Itália - Monza', 5793);
insert into circuito (cod_pais, nome, extensao)values (14, 'GP da Bélgica - Spa-Francorchamps', 6973);
insert into circuito (cod_pais, nome, extensao)values (11, 'GP do Japão - Fuji', 4563);
insert into circuito (cod_pais, nome, extensao)values (22, 'GP da China - Xangai', 5451);
insert into circuito (cod_pais, nome, extensao)values (1,'GP do Brasil - Interlagos',4309);