insert into equipe (cod_pais, nome) values (4, 'McLaren-Mercedes');
insert into equipe (cod_pais, nome) values (15, 'Renault F1 Team');
insert into equipe (cod_pais, nome) values (5, 'Scuderia Ferrari');
insert into equipe (cod_pais, nome) values (11, 'Honda F1 Racing Team');
insert into equipe (cod_pais, nome) values (6, 'BMW Sauber');
insert into equipe (cod_pais, nome) values (11, 'Toyota F1 Team');
insert into equipe (cod_pais, nome) values (9, 'Red Bull Racing');
insert into equipe (cod_pais, nome) values (4, 'Williams Toyota');
insert into equipe (cod_pais, nome) values (5, 'Toro Rosso');
insert into equipe (cod_pais, nome) values (7, 'Spyker F1 Team');
insert into equipe (cod_pais, nome) values (11, 'Super Aguri');